server:
  port: 0
spring:
  application:
    name: card-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            customer-service:
              - uri: http://localhost:1026
    loadbalancer:
      retry:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_JDBC_URL};SCHEMA=CARD_SCHEMA
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    liquibase-schema: CARD_SCHEMA
    default-schema: CARD_SCHEMA
    change-log: classpath:/db/migration/db.changelog-master.yaml
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVICE_URL}
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json