server:
  port: ${SERVER_PORT:1024}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:./RestBank;AUTO_SERVER=TRUE;SCHEMA=CARD_SCHEMA}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
    default-schema: CARD_SCHEMA
    liquibase-schema: CARD_SCHEMA
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.105:7080/realms/bank-realm
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json