### Login / Each request create rewrite auth_token for intellij
POST http://localhost:1024/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
> {%
    client.global.set("auth_token", response.body.jwt);
%}

### Account pagination
GET http://localhost:1024/api/v1/accounts?
    page={{page}}&
    size={{size}}
Authorization: Bearer {{auth_token}}

### Get account by id
GET http://localhost:1024/api/v1/accounts/{{userId}}
Authorization: Bearer {{auth_token}}

### Card pagination
GET http://localhost:1024/api/v1/cards?page={{page}}&size={{size}}
Authorization: Bearer {{auth_token}}

### Creating an account by an administrator
POST http://localhost:1024/api/v1/accounts
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "johndoee",
  "password": "P@ssw0rd!",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "phone": "+1-800-555-1234",
  "roleId": 2
}

### Creating a card for a user by the admin
POST http://localhost:1024/api/v1/cards?userId={{userId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Get a card by ID
GET http://localhost:1024/api/v1/cards/3
Authorization: Bearer {{auth_token}}

### Request to block the card by the user
POST http://localhost:1024/api/v1/cards/1/block-request
Authorization: Bearer {{auth_token}}

### Approve the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-approve
Authorization: Bearer {{auth_token}}

### Reject the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-reject
Authorization: Bearer {{auth_token}}

### Transfer money between users cards
POST http://localhost:1024/api/v1/cards/transfer?
    fromCard=2227529027274944&
    toCard=5515251215481686&
    amount=1
Authorization: Bearer {{auth_token}}

### Delete account by id
DELETE http://localhost:1024/api/v1/accounts/{{userId}}
Authorization: Bearer {{auth_token}}