### Account pagination
GET http://localhost:1024/api/v1/accounts?
    page={{page}}&
    size={{size}}
Authorization: Basic {{adminBasic}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### Get account by id
GET http://localhost:1024/api/v1/accounts/{{userId}}
Authorization: Basic {{adminBasic}}

### Card pagination
GET http://localhost:1024/api/v1/cards?page={{page}}&size={{size}}
Authorization: Basic {{adminBasic}}

### Creating an account by an administrator
POST http://localhost:1024/api/v1/accounts
Authorization: Basic {{userBasic}}
Content-Type: application/json

{
  "username": "johndoee",
  "password": "P@ssw0rd!",
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "phone": "+1-800-555-1234",
  "roleId": 2
}

### Creating a card for a user by the admin
POST http://localhost:1024/api/v1/cards?userId={{userId}}
Authorization: Basic {{adminBasic}}
Content-Type: application/json

### Get a card by ID
GET http://localhost:1024/api/v1/cards/1
Authorization: Basic {{userBasic}}

### Request to block the card by the user
POST http://localhost:1024/api/v1/cards/1/block-request
Authorization: Basic {{userBasic}}

### Approve the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-approve
Authorization: Basic {{adminBasic}}

### Reject the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-reject
Authorization: Basic {{adminBasic}}

### Transfer money between users cards
POST http://localhost:1024/api/v1/cards/transfer?
    fromCard=2227529027274944&
    toCard=5515251215481686&
    amount=1
Authorization: Basic {{userBasic}}

### Delete account by id
DELETE http://localhost:1024/api/v1/accounts/5
Authorization: Basic {{adminBasic}}