server:
  port: ${SERVER_PORT:1024}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/restbank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
jwt:
  secret: ${JWT_SECRET:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlciIsInBhc3N3b3JkIjoidXNlciIsImlhdCI6MTc1MzM1OTg1NH0.b8NZsCt31u_8-EdWUTbZYJflKgwO1n6FixaRnwoO65I"}
  expiration: ${JWT_EXPIRATION:360000}