#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: ${SERVER_PORT:1024}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:./RestBank;AUTO_SERVER=TRUE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/docs/
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: accounts
      display-name: Accounts API
      paths-to-match: /api/v1/accounts/**
    - group: cards
      display-name: Cards API
      paths-to-match: /api/v1/cards/**
  swagger-ui:
    path: /docs
    enabled: true
    urls:
      - name: From File
        url: /openapi.yaml
      - name: Generated API
        url: /v3/api-docs