#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: ${SERVER_PORT:1024}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.0.105:5432/restbank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    path: /api-docs