### Account pagination
GET http://localhost:1024/api/v1/accounts?
    page={{page}}&
    size={{size}}
Authorization: Basic {{adminBasic}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### Card pagination
GET http://localhost:1024/api/v1/cards?page={{page}}&size={{size}}
Authorization: Basic {{adminBasic}}

### Creating an account by an administrator
POST http://localhost:1024/api/v1/accounts
Authorization: Basic {{userBasic}}
Content-Type: application/json
Accept-Language: en

{
  "username": "",
  "password": "user",
  "firstName": "",
  "lastName": "Last",
  "email": "e@mail.com",
  "phone": "+71111155555",
  "role_id": 2
}

### Creating a card for a user by the admin
POST http://localhost:1024/api/v1/cards?userId={{userId}}
Authorization: Basic {{adminBasic}}
Content-Type: application/json

### Get a card by ID
GET http://localhost:1024/api/v1/cards/35
Authorization: Basic {{userBasic}}

### Request to block the card by the user
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-request
Authorization: Basic {{userBasic}}

### Approve the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-approve
Authorization: Basic {{adminBasic}}

### Reject the request to block the card by the administrator
POST http://localhost:1024/api/v1/cards/{{cardId}}/block-reject
Authorization: Basic {{adminBasic}}

### Transfer money between users cards
POST http://localhost:1024/api/v1/cards/transfer?
    fromCard=2222064603775853&
    toCard=2223629877584998&
    amount=1
Authorization: Basic bWF4Om1heA==