name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5-alpine3.21
        env:
          POSTGRES_DB: restbank
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # В Gitea возможно надо заменить на "git clone"

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # В Gitea нужно установить JDK через скрипт, или использовать образ с JDK
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
          cache-dependency-path:
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties

      - name: Run tests
        run: ./gradlew clean test --no-daemon --stacktrace
      - run: ./gradlew build --no-daemon
