server:
  port: 0
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_JDBC_URL}?currentSchema=customer_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    liquibase-schema: CUSTOMER_SCHEMA
    default-schema: CUSTOMER_SCHEMA
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: user-sync-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: customer-service
  data:
    jdbc:
      dialect: postgresql
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
logging:
  level:
    com.netflix.discovery: warn
    com.netflix.eureka: warn