server:
  port: 0
  forward-headers-strategy: framework
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_JDBC_URL}?currentSchema=customer_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    liquibase-schema: customer_schema
    default-schema: customer_schema
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: user-sync-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: customer-service
  data:
    jdbc:
      dialect: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    registry-fetch-interval-seconds: 1
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
logging:
  level:
    com.netflix.discovery: warn
    com.netflix.eureka: warn
management:
  server:
    port: 8081
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs
  api-path-segment: customers