server:
  port: 0
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_JDBC_URL};SCHEMA=CUSTOMER_SCHEMA;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    liquibase-schema: CUSTOMER_SCHEMA
    default-schema: CUSTOMER_SCHEMA
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: 192.168.0.105:9092
      group-id: user-sync-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: customer-service
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVICE_URL}
  instance:
    prefer-ip-address: true
