# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

version: "3.8"

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:1024"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: restbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.
