include:
  - docker-support.yml
  - docker-services.yml
services:
  connector-setup:
    image: alpine:3.22.1
    restart: no
    depends_on:
      debezium:
        condition: service_healthy
      customer-service:
        condition: service_healthy
    volumes:
      - ./connectors:/data/connectors
    env_file:
      - ./.env
    command:
      - sh
      - -c
      - |
        apk add --no-cache curl gettext
        /data/connectors/register-all-connectors.sh
    networks:
      - restbank-net