services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${SERVER_PORT}:1024"
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: restbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
