spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: false
server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  server:
    port: 8081