spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: false
server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false