server:
  port: ${API_GATEWAY_PORT}
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: auth-service-api-docs
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth, /api/v1/auth
        - id: customer-service-api-docs
          uri: lb://customer-service
          predicates:
            - Path=/customers/v3/api-docs
          filters:
            - RewritePath=/customers/v3/api-docs, /v3/api-docs
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - TokenRelay=
            - AddRequestHeader=X-Service-Call, gateway
            - RewritePath=/customers(?<path>/.*)?, /api/v1/customers\${path}
        - id: card-service-api-docs
          uri: lb://card-service
          predicates:
            - Path=/cards/v3/api-docs
          filters:
            - RewritePath=/cards/v3/api-docs, /v3/api-docs
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/cards/**
          filters:
            - TokenRelay=
            - RewritePath=/cards(?<path>/.*)?, /api/v1/cards\${path}
            - name: CircuitBreaker
              args:
                name: cardCircuitBreaker
                fallbackUri: forward:/fallback
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${API_GATEWAY_KEYCLOAK_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  liquibase:
    enabled: false

resilience4j:
  circuitbreaker:
    configs:
      defaults:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081
springdoc:
  swagger-ui:
    urls:
      - name: Customer Service
        url: /customers/v3/api-docs
      - name: Card Service
        url: /cards/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
    path: /docs