server:
  port: ${API_GATEWAY_PORT}
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${API_GATEWAY_KEYCLOAK_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  liquibase:
    enabled: false

resilience4j:
  circuitbreaker:
    configs:
      defaults:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
management:
  server:
    port: 8081
springdoc:
  swagger-ui:
    urls:
      - name: Customer Service
        url: /customers/v3/api-docs
      - name: Card Service
        url: /cards/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
    path: /docs